import { HttpService } from '@nestjs/axios';
import { Account, Detector, MarketType, Order, ConnectorType, OrderType, TimeFrame, Candle, Inspector, OrderSourceType, Advisor, Symbol, Provider } from '@barfinex/types';
export declare class ConnectorService {
    private http;
    constructor(http: HttpService);
    private isDebug;
    private readonly logger;
    private getCallerName;
    private logStart;
    private logSuccess;
    private logError;
    checkApiUrlWithСonnectorType(url: string): void;
    checkApiUrl(url: string): void;
    openOrder(options: {
        order: Order;
        providerRestApiUrl: string;
    }): Promise<Order>;
    closeOrder(options: {
        order: Order;
        providerRestApiUrl: string;
    }): Promise<Order>;
    closeAllOrders(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
        symbol?: Symbol;
        type?: OrderType;
        orderSource: OrderSourceType;
    }): Promise<Order[]>;
    cancelOrder(options: {
        order: Order;
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
    }): Promise<Order>;
    cancelAllOrders(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
        symbol?: Symbol;
        type?: OrderType;
        orderSource: OrderSourceType;
    }): Promise<Order[]>;
    updateOrder(options: {
        order: Order;
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
    }): Promise<Order>;
    getOrder(options: {
        order: Order;
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
    }): Promise<Order>;
    getOrders(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
    }): Promise<Order[]>;
    getActiveOrders(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
    }): Promise<Order[]>;
    getCancelledOrders(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
    }): Promise<Order[]>;
    getCandles(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
        symbol: Symbol;
        interval: TimeFrame;
    }): Promise<Candle[]>;
    getProviderOptions(options: {
        providerRestApiUrl: string;
    }): Promise<Provider>;
    getAccount(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
    }): Promise<Account>;
    changeAccountSymbolLeverage(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
        symbol: Symbol;
        newLeverage: number;
    }): Promise<Account>;
    getInspectors(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
    }): Promise<Inspector[]>;
    getInspector(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
        inspectorKey: string;
    }): Promise<Inspector>;
    registerInspector(options: {
        providerRestApiUrl: string;
        inspector: Inspector;
    }): Promise<Inspector>;
    updateInspector(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
        inspector: Inspector;
    }): Promise<Inspector>;
    getDetectors(options: {
        providerRestApiUrl: string;
    }): Promise<Detector[]>;
    getDetector(options: {
        providerRestApiUrl: string;
        detectorKey: string;
    }): Promise<Detector>;
    registerDetector(options: {
        providerRestApiUrl: string;
        detector: Detector;
    }): Promise<Detector>;
    updateDetector(options: {
        providerRestApiUrl: string;
        detector: Detector;
    }): Promise<Detector>;
    getAdvisors(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
    }): Promise<Advisor[]>;
    getAdvisor(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
        advisorKey: string;
    }): Promise<Advisor>;
    advisorRegistration(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
        advisor: Advisor;
    }): Promise<Advisor>;
    advisorUpdate(options: {
        providerRestApiUrl: string;
        connectorType: ConnectorType;
        marketType: MarketType;
        advisor: Advisor;
    }): Promise<Advisor>;
    request(method: 'get' | 'post' | 'put', url: string, params: any, defaultValue: any, methodName?: string): import("rxjs").Observable<any>;
}
